title: Fantasy NHL Optimizer
description: "Hi! Iâ€™m Henry Lange, a 17-year-old senior at Barrington High School in Illinois. Hockey has shaped my life since I was just four years old. I worked my way up to being a goalie for Team Illinois, and last year I played up an age level with the U18 West Dundee Leafs, the #1 ranked AA team in the country. After spending my summer diving into sports data analysis, I realized something: the competition I loved on the ice, like reading complex patterns and making split-second decisions under pressure, translates perfectly to quantitative finance. As I did more research into this field, seeing the intersection between math, algorithms, and trading drew me in even more. Now, I am trying to develop skills that will take my competitive nature from the ice to financial markets." 
baseurl: "" 
url: "https://HenryLange.github.io/fantasy-nhl-optimizer"
theme: minima
paginate: 5

# fixing links
url: "https://henrylange.github.io"
baseurl: "/fantasy-nhl-optimizer"

header_pages:
  - code/index.md 

# trying to get code to be formatted/appear better in posts
markdown: kramdown
highlighter: rouge
